### PR TITLE
Propagate defaults to operation callback

### LINKED ISSUE #37: Process defaultValues in inputObject
Follows up https://github.com/tarantool/graphql/pull/35

https://github.com/tarantool/graphql/pull/35#discussion_r783351688 points out that defaultValues of inputObjects is inaccessible in callbacks. Thus the feature is broken. It should be verified and fixed.

### PR DESCRIPTION
**Pull request by no1seman**
Before this PR there is no fast and convenient way to get
operation and directives defaults set when creating the schema.

Now it's possible, operation and directives default can be easily found
is in the #3 argument of callback - map "info". The keys are:

defaultValues - for operation defaults
directivesDefaultValues - for directives defaults

There will be no defaults propageted by default. To make it available must set 2 options:

schema.create(config, name, {defaultValues = true, directivesDefaultValues = true})

This will done to make schema creation a little be faster when one don't need defaults to be propagated.

closes: https://github.com/tarantool/graphql/issues/37

### CODE REVIEW

File: test/integration/graphql_test.lua [hunk 1]
```diff
@@ -1804,3 +1804,183 @@ function g.test_skip_include_directives()
...
+                kind = types.float,
+                defaultValue = 1.1,
+            },
+            nested_long_arg = {
+                kind = types.long,
+                defaultValue = 2^50,
+            },
+            nested_list_scalar_arg = {
+                kind = types.list(types.string),
+                -- defaultValue seems illogical
```
Comment (DifferentialOrange) [inline test/integration/graphql_test.lua:1910]: Do someone specifies inputObject field as scalar? It also seems a bit illogical

Comment (DifferentialOrange) [reply test/integration/graphql_test.lua:1910]: Also I don't understand what we're try to test here (lines 1841-1844) if there aren't any default values

File: graphql/schema.lua [hunk 2]
```diff
@@ -8,10 +8,11 @@ end
 local schema = {}
 schema.__index = schema
 
-function schema.create(config, name)
+function schema.create(config, name, opts)
```
Comment (DifferentialOrange) [inline graphql/schema.lua:11]: 1. Why do we need opts for this?
2. Why default values is disabled by default?
Is this about performance optimization?

File: test/integration/graphql_test.lua [hunk 3]
```diff
@@ -1804,3 +1804,183 @@ function g.test_skip_include_directives()
...
+            onField = true,
+        })
+    }
+
+    local result = {
+        defaultValues = {
+            boolean_arg = false,
+            int_arg = 1,
+            float_arg = 1.1,
+            long_arg = 1125899906842624LL,
```
Comment (DifferentialOrange) [inline test/integration/graphql_test.lua]: Use `2^50` here or `1125899906842624LL` above for consistency

File: graphql/schema.lua [hunk 4]
```diff
@@ -34,9 +35,101 @@ function schema.create(config, name)
...
+
+  if nodeType.__type == 'Scalar' then
+    return node.defaultValue
+  end
+
+  node.fields = type(node.fields) == 'function' and node.fields() or node.fields
+
+  if nodeType.__type == 'Object' or nodeType.__type == 'InputObject' then
+    for fieldName, field in pairs(nodeType.fields or {}) do
+      local fieldDefaultValue = self:extractDefaults(field)
```
Comment (DifferentialOrange) [inline graphql/schema.lua:77]: So nested structures is supported here? Do there any other issues left for serializing nested structures? (Or I am confusing it with something)

File: graphql/schema.lua [hunk 5]
```diff
@@ -117,7 +210,7 @@ function schema:generateDirectiveMap()
           if argumentType == nil then
             error('Must supply type for argument "' .. name .. '" on "' .. directive.name .. '"')
           end
-          argumentType.defaultValue = argument.defaultValue
+          -- argumentType.defaultValue = argument.defaultValue
```
Comment (DifferentialOrange) [inline graphql/schema.lua]: Rebase on master after https://github.com/tarantool/graphql/pull/44 merge

File: test/integration/graphql_test.lua (hunk 1 above)
Comment (no1seman) [reply test/integration/graphql_test.lua:1910]: It's an example of illogical to have root defaults for a list and inputObject. Also it's a point of a disscussion

File: graphql/schema.lua (hunk 2 above)
Comment (no1seman) [reply graphql/schema.lua:11]: In real app's we have to recreate schema on every schema change. If we don't use defaults why to do useless job on every schema.create? Also that pattern seems to be friendly for existing apps where no any usage of defaults maps in callbacks.

File: graphql/schema.lua (hunk 4 above)
Comment (no1seman) [reply graphql/schema.lua:77]: self:extractDefaults - recursively called so the answer is Yes

File: graphql/schema.lua (hunk 5 above)
Comment (no1seman) [reply graphql/schema.lua]: We didn't discussed #44 and made any decisions. So when it will be done I will rebase this PR on #44

File: test/integration/graphql_test.lua (hunk 1 above)
Comment (no1seman) [reply test/integration/graphql_test.lua:1910]: Merged

File: test/integration/graphql_test.lua (hunk 3 above)
Comment (no1seman) [reply test/integration/graphql_test.lua]: Fixed

File: graphql/schema.lua (hunk 5 above)
Comment (no1seman) [reply graphql/schema.lua]: Fixed by merging with #44

File: graphql/schema.lua (hunk 2 above)
Comment (DifferentialOrange) [reply graphql/schema.lua:11]: Sounds convincingly

File: graphql/schema.lua (hunk 5 above)
Comment (DifferentialOrange) [reply graphql/schema.lua]: Since #44 is merged now, you can rebase the branch

**Review by DifferentialOrange — APPROVED** [review]
Seems ok. As always, thank you for your PR! You'll need to rebase on master and fix possible conflicts with #44 before merge

**Review by Totktonada — APPROVED** [review]
The idea is okay. Unlikely I can add something by digging into the code, so I'll approve.

**Review by Totktonada — APPROVED** [review]
