### PR TITLE
Fix silently cast huge cdata numbers to null

### LINKED ISSUE #17: GraphQL silently cast huge cdata numbers to null
in code:
```lua
object.version = -1ULL
```

in query such field silently return `null`.

### PR DESCRIPTION
**Pull request by no1seman**
It's quite worth solution but seems that it works

closes: https://github.com/tarantool/graphql/issues/17

### CODE REVIEW

File: graphql/types.lua [hunk 1]
```diff
@@ -299,9 +299,7 @@ end
 local function coerceLong(value)
   if value ~= nil then
     value = tonumber64(value)
-    if not isLong(value) then return end
```
Comment (olegrok) [inline graphql/types.lua:302]: It's quite strange logic. I guess we could move isLong at this function start and raise an error if condition is wrong. Currently user could return even string instead of number and in some cases (if this string contains numeric values) user gets correct result.

Comment (no1seman) [reply graphql/types.lua:302]: Seems that this must be fxed not only in this function but everywhere in types submodule. Filed a new issue: https://github.com/tarantool/graphql/issues/56

Comment (no1seman) [reply graphql/types.lua:302]: Actually isValueOfTheType called from validate* routines and there if isValueOfTheType fails error is raised. We can raise error in isValueOfTheType but this leads to use pcall in validate* routines because we have to return meanningfull error and in isValueOfTheType we don't have enougth context info: variable or field name, etc.

File: graphql/types.lua [hunk 2]
```diff
@@ -289,7 +289,7 @@ local function isLong(value)
     if ffi.istype('int64_t', value) then
       return true
     elseif ffi.istype('uint64_t', value) then
-      return value < 2^63
+      return true
     end
```
Comment (olegrok) [inline graphql/types.lua]: I suggest to do as for long.

https://github.com/tarantool/graphql/commit/462041066ce87b6f5b62711420222ba89c9e6aae#diff-48b353c0afde7d4bcd91610c7f61fb2cedaa61b218c4165d943aa8f9780fa9c2R336-R338

**Review by olegrok — APPROVED** [review]

**Review by DifferentialOrange — APPROVED** [review]
Followed up by https://github.com/tarantool/graphql/issues/56 , https://github.com/tarantool/graphql/issues/61
