### PR TITLE
Accept cdata number as float and forbid NaN/Inf

### LINKED ISSUE #47: Wrong variable "var" for the Scalar "Float" if value is greater than 10^15

### PR DESCRIPTION
**Pull request by Totktonada**
This pull request contains two changes related to processing of variables of the `Float` type.

## Accept a cdata number as value of a Float variable

It is quite usual that a floating point number is encoded using JSON, goes over HTTP, received on tarantool server, decoded from JSON and passed as a variable into the GraphQL executor.

A number out of the [-10^14+1; 10^14-1] range is decoded into Lua as cdata number[^1] to don't loss the precision. A JSON decoder don't know that we intend to use this value as the floating point one and chooses the conservative option: decode the value into cdata number to don't loss the precision.

[^1]: `cdata<int64_t>` or `cdata<uint64_t>`

In GraphQL we know that it is actually the floating point value (disregarding its representation in Lua). So it looks correct to accept a cdata number as value of a Float variable.

The similar idea was expressed in https://github.com/tarantool/tarantool/issues/5933 against tarantool itself: let it accept a number without fractional part as a value suitable for the `float` field type.

## Forbid NaN and Infinity as a value Float type

The GraphQL specification explicitly forbids it: 

> Non-finite floating-point internal values (NaN and Infinity) cannot
> be coerced to Float and must raise a field error.

http://spec.graphql.org/October2021/#sec-Float

----

Fixes #47
Supersedes PR #48

### CODE REVIEW

**Review by no1seman — APPROVED** [review]

File: graphql/types.lua [hunk 1]
```diff
@@ -317,8 +317,27 @@ types.long = types.scalar({
...
+end
+
 local function isFloat(value)
-  return type(value) == 'number'
+  -- http://spec.graphql.org/October2021/#sec-Float
+  --
+  -- > Non-finite floating-point internal values (NaN and Infinity) cannot be
+  -- > coerced to Float and must raise a field error.
+  if type(value) == 'number' then
+      return isfinite(value)
```
Comment (olegrok) [inline graphql/types.lua]: Indent seems to be broken here. Below you use 2 spaces.

File: test/integration/graphql_test.lua [hunk 2]
```diff
@@ -2051,3 +2051,65 @@ g.test_propagate_defaults_to_callback = function()
...
+            },
+            resolve = callback,
+        }
+    }
+
+    -- 2^64-1
+    local variables = {x = 18446744073709551615ULL}
+    local res = check_request(query, query_schema, nil, nil, {variables = variables})
+    t.assert_type(res, 'table')
+    t.assert_almost_equals(res.test, 18446744073709551615)
```
Comment (olegrok) [inline test/integration/graphql_test.lua:2079]: It's worth to test not only variables but arguments as well.

**Review by olegrok — APPROVED** [review]

File: test/integration/graphql_test.lua (hunk 2 above)
Comment (Totktonada) [reply test/integration/graphql_test.lua:2079]: It is not strictly related to what is reported in the issue, but okay: added it with a remark regarding relation to the issue.

File: graphql/types.lua (hunk 1 above)
Comment (Totktonada) [reply graphql/types.lua]: Overlooked it, thanks! Fixed.

**Review by olegrok — APPROVED** [review]
